const jobs = [
  {
    _id: 1,
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Remote",
    description:
      "We are looking for a skilled Frontend Developer to join our team.",
    requirements: ["React", "JavaScript", "CSS", "HTML"],
    salary: "$80,000 - $100,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "jobs@techcorp.com",
    applyLink: "https://techcorp.com/apply/frontend-dev",
  },
  {
    _id: 2,
    title: "Backend Developer",
    company: "CodeBase Inc.",
    location: "New York, NY",
    description:
      "Seeking an experienced Backend Developer to build scalable APIs.",
    requirements: ["Node.js", "Express", "MongoDB", "REST APIs"],
    salary: "$90,000 - $120,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "careers@codebase.com",
    applyLink: "https://codebase.com/apply/backend-dev",
  },
  {
    _id: 3,
    title: "UI/UX Designer",
    company: "Designify",
    location: "San Francisco, CA",
    description: "Join our team as a creative UI/UX Designer.",
    requirements: ["Figma", "Sketch", "Adobe XD", "Prototyping"],
    salary: "$70,000 - $90,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "hr@designify.com",
    applyLink: "https://designify.com/apply/uiux-designer",
  },
  {
    _id: 4,
    title: "Data Scientist",
    company: "DataWorks",
    location: "Remote",
    description:
      "Looking for a Data Scientist to analyze and interpret complex data.",
    requirements: ["Python", "Machine Learning", "SQL", "Data Visualization"],
    salary: "$100,000 - $130,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "jobs@dataworks.com",
    applyLink: "https://dataworks.com/apply/data-scientist",
  },
  {
    _id: 5,
    title: "DevOps Engineer",
    company: "CloudOps",
    location: "Austin, TX",
    description: "Hiring a DevOps Engineer to manage cloud infrastructure.",
    requirements: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    salary: "$95,000 - $115,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "careers@cloudops.com",
    applyLink: "https://cloudops.com/apply/devops-engineer",
  },
  {
    _id: 6,
    title: "Mobile App Developer",
    company: "Appify",
    location: "Seattle, WA",
    description: "We need a Mobile App Developer to create innovative apps.",
    requirements: ["React Native", "iOS", "Android", "JavaScript"],
    salary: "$85,000 - $105,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "jobs@appify.com",
    applyLink: "https://appify.com/apply/mobile-dev",
  },
  {
    _id: 7,
    title: "Product Manager",
    company: "InnovateX",
    location: "Boston, MA",
    description: "Seeking a Product Manager to lead product development.",
    requirements: ["Agile", "Scrum", "Leadership", "Communication"],
    salary: "$110,000 - $140,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "careers@innovatex.com",
    applyLink: "https://innovatex.com/apply/product-manager",
  },
  {
    _id: 8,
    title: "Cybersecurity Analyst",
    company: "SecureNet",
    location: "Washington, DC",
    description:
      "Join us as a Cybersecurity Analyst to protect digital assets.",
    requirements: ["Cybersecurity", "Penetration Testing", "Firewalls", "SIEM"],
    salary: "$90,000 - $120,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "jobs@securenet.com",
    applyLink: "https://securenet.com/apply/cybersecurity-analyst",
  },
  {
    _id: 9,
    title: "AI Engineer",
    company: "AI Solutions",
    location: "Remote",
    description:
      "Looking for an AI Engineer to develop cutting-edge AI models.",
    requirements: ["Python", "TensorFlow", "PyTorch", "Deep Learning"],
    salary: "$120,000 - $150,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "careers@aisolutions.com",
    applyLink: "https://aisolutions.com/apply/ai-engineer",
  },
  {
    _id: 10,
    title: "Technical Writer",
    company: "DocuTech",
    location: "Chicago, IL",
    description: "Hiring a Technical Writer to create clear documentation.",
    requirements: ["Technical Writing", "API Documentation", "Markdown", "Git"],
    salary: "$60,000 - $80,000",
    jobType: "Full-Time",
    postedAt: new Date().toLocaleDateString(),
    contactEmail: "hr@docutech.com",
    applyLink: "https://docutech.com/apply/technical-writer",
  },
];

export default jobs;
